name: BookMyShow Notifier

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run BookMyShow checker
        run: python BookMyShow.py --movie "hit" --cinema "pvr" --date "20240502" --regionCode "VIZA" --format "2D"
        env:
          GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
          GMAIL_RECEIVER: ${{ secrets.GMAIL_RECEIVER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
